
//FACILITADORES - MTTO
const PREFIX="/facilitador"
export const GET_FACILITADORES_MTO_INDEX=PREFIX+"/";
export const POST_FACILITADORES_MTO_STORE=PREFIX+"/";
export const PUT_FACILITADORES_MTO_STORE=PREFIX+"/";
export const PUT_FACILITADORES_MTO_ACTIVO=PREFIX+"/";
export const GET_FACILITADORES_MTO_INICIALIZAR=PREFIX+"/inicializar"